import Head from 'next/head';
import Header from "../header/header";

const Layout = ({children,title}) => {
    return(
        <div className="bg-base md:pt-12">
            <div className="max-w-screen-xl mx-auto">
                <Head>
                    <title>{title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="pt-10 px-10 md:px-5 border-r-50 md:border-l-0 border-black md:border-transparent min-h-screen">
                    <Header/>
                    {children}
                </div>
            </div>
        </div>
    )
}

export default Layout;