import Head from 'next/head'

const Layout = ({children,title}) => {
    return(
        <div className="bg-base md:pt-12">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="pt-10 px-10 border-r-50 md:pr-10 md:border-l-0 border-black md:border-transparent min-h-screen">
                {children}
            </div>
        </div>
    )
}

export default Layout;